/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResidentialServicesRouteImport } from './routes/residential-services'
import { Route as RenovationServicesRouteImport } from './routes/renovation-services'
import { Route as PlumbingServicesRouteImport } from './routes/plumbing-services'
import { Route as PaintingServicesRouteImport } from './routes/painting-services'
import { Route as KitchenRemodelingRouteImport } from './routes/kitchen-remodeling'
import { Route as GeneralContractingRouteImport } from './routes/general-contracting'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as ElectricalServicesRouteImport } from './routes/electrical-services'
import { Route as DrywallServicesRouteImport } from './routes/drywall-services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommercialServicesRouteImport } from './routes/commercial-services'
import { Route as BathroomRemodelingRouteImport } from './routes/bathroom-remodeling'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasTheodoreAlRouteImport } from './routes/areas/theodore-al'
import { Route as AreasPascagoulaMsRouteImport } from './routes/areas/pascagoula-ms'
import { Route as AreasOceanSpringsMsRouteImport } from './routes/areas/ocean-springs-ms'
import { Route as AreasMossPointMsRouteImport } from './routes/areas/moss-point-ms'
import { Route as AreasGrandBayAlRouteImport } from './routes/areas/grand-bay-al'
import { Route as AreasGautierMsRouteImport } from './routes/areas/gautier-ms'
import { Route as AreasDibervilleMsRouteImport } from './routes/areas/diberville-ms'
import { Route as AreasBiloxiMsRouteImport } from './routes/areas/biloxi-ms'

const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentialServicesRoute = ResidentialServicesRouteImport.update({
  id: '/residential-services',
  path: '/residential-services',
  getParentRoute: () => rootRouteImport,
} as any)
const RenovationServicesRoute = RenovationServicesRouteImport.update({
  id: '/renovation-services',
  path: '/renovation-services',
  getParentRoute: () => rootRouteImport,
} as any)
const PlumbingServicesRoute = PlumbingServicesRouteImport.update({
  id: '/plumbing-services',
  path: '/plumbing-services',
  getParentRoute: () => rootRouteImport,
} as any)
const PaintingServicesRoute = PaintingServicesRouteImport.update({
  id: '/painting-services',
  path: '/painting-services',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRemodelingRoute = KitchenRemodelingRouteImport.update({
  id: '/kitchen-remodeling',
  path: '/kitchen-remodeling',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralContractingRoute = GeneralContractingRouteImport.update({
  id: '/general-contracting',
  path: '/general-contracting',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricalServicesRoute = ElectricalServicesRouteImport.update({
  id: '/electrical-services',
  path: '/electrical-services',
  getParentRoute: () => rootRouteImport,
} as any)
const DrywallServicesRoute = DrywallServicesRouteImport.update({
  id: '/drywall-services',
  path: '/drywall-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialServicesRoute = CommercialServicesRouteImport.update({
  id: '/commercial-services',
  path: '/commercial-services',
  getParentRoute: () => rootRouteImport,
} as any)
const BathroomRemodelingRoute = BathroomRemodelingRouteImport.update({
  id: '/bathroom-remodeling',
  path: '/bathroom-remodeling',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasTheodoreAlRoute = AreasTheodoreAlRouteImport.update({
  id: '/areas/theodore-al',
  path: '/areas/theodore-al',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasPascagoulaMsRoute = AreasPascagoulaMsRouteImport.update({
  id: '/areas/pascagoula-ms',
  path: '/areas/pascagoula-ms',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasOceanSpringsMsRoute = AreasOceanSpringsMsRouteImport.update({
  id: '/areas/ocean-springs-ms',
  path: '/areas/ocean-springs-ms',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasMossPointMsRoute = AreasMossPointMsRouteImport.update({
  id: '/areas/moss-point-ms',
  path: '/areas/moss-point-ms',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasGrandBayAlRoute = AreasGrandBayAlRouteImport.update({
  id: '/areas/grand-bay-al',
  path: '/areas/grand-bay-al',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasGautierMsRoute = AreasGautierMsRouteImport.update({
  id: '/areas/gautier-ms',
  path: '/areas/gautier-ms',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasDibervilleMsRoute = AreasDibervilleMsRouteImport.update({
  id: '/areas/diberville-ms',
  path: '/areas/diberville-ms',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasBiloxiMsRoute = AreasBiloxiMsRouteImport.update({
  id: '/areas/biloxi-ms',
  path: '/areas/biloxi-ms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bathroom-remodeling': typeof BathroomRemodelingRoute
  '/commercial-services': typeof CommercialServicesRoute
  '/contact': typeof ContactRoute
  '/drywall-services': typeof DrywallServicesRoute
  '/electrical-services': typeof ElectricalServicesRoute
  '/estimate': typeof EstimateRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/general-contracting': typeof GeneralContractingRoute
  '/kitchen-remodeling': typeof KitchenRemodelingRoute
  '/painting-services': typeof PaintingServicesRoute
  '/plumbing-services': typeof PlumbingServicesRoute
  '/renovation-services': typeof RenovationServicesRoute
  '/residential-services': typeof ResidentialServicesRoute
  '/reviews': typeof ReviewsRoute
  '/service-areas': typeof ServiceAreasRoute
  '/areas/biloxi-ms': typeof AreasBiloxiMsRoute
  '/areas/diberville-ms': typeof AreasDibervilleMsRoute
  '/areas/gautier-ms': typeof AreasGautierMsRoute
  '/areas/grand-bay-al': typeof AreasGrandBayAlRoute
  '/areas/moss-point-ms': typeof AreasMossPointMsRoute
  '/areas/ocean-springs-ms': typeof AreasOceanSpringsMsRoute
  '/areas/pascagoula-ms': typeof AreasPascagoulaMsRoute
  '/areas/theodore-al': typeof AreasTheodoreAlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bathroom-remodeling': typeof BathroomRemodelingRoute
  '/commercial-services': typeof CommercialServicesRoute
  '/contact': typeof ContactRoute
  '/drywall-services': typeof DrywallServicesRoute
  '/electrical-services': typeof ElectricalServicesRoute
  '/estimate': typeof EstimateRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/general-contracting': typeof GeneralContractingRoute
  '/kitchen-remodeling': typeof KitchenRemodelingRoute
  '/painting-services': typeof PaintingServicesRoute
  '/plumbing-services': typeof PlumbingServicesRoute
  '/renovation-services': typeof RenovationServicesRoute
  '/residential-services': typeof ResidentialServicesRoute
  '/reviews': typeof ReviewsRoute
  '/service-areas': typeof ServiceAreasRoute
  '/areas/biloxi-ms': typeof AreasBiloxiMsRoute
  '/areas/diberville-ms': typeof AreasDibervilleMsRoute
  '/areas/gautier-ms': typeof AreasGautierMsRoute
  '/areas/grand-bay-al': typeof AreasGrandBayAlRoute
  '/areas/moss-point-ms': typeof AreasMossPointMsRoute
  '/areas/ocean-springs-ms': typeof AreasOceanSpringsMsRoute
  '/areas/pascagoula-ms': typeof AreasPascagoulaMsRoute
  '/areas/theodore-al': typeof AreasTheodoreAlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bathroom-remodeling': typeof BathroomRemodelingRoute
  '/commercial-services': typeof CommercialServicesRoute
  '/contact': typeof ContactRoute
  '/drywall-services': typeof DrywallServicesRoute
  '/electrical-services': typeof ElectricalServicesRoute
  '/estimate': typeof EstimateRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/general-contracting': typeof GeneralContractingRoute
  '/kitchen-remodeling': typeof KitchenRemodelingRoute
  '/painting-services': typeof PaintingServicesRoute
  '/plumbing-services': typeof PlumbingServicesRoute
  '/renovation-services': typeof RenovationServicesRoute
  '/residential-services': typeof ResidentialServicesRoute
  '/reviews': typeof ReviewsRoute
  '/service-areas': typeof ServiceAreasRoute
  '/areas/biloxi-ms': typeof AreasBiloxiMsRoute
  '/areas/diberville-ms': typeof AreasDibervilleMsRoute
  '/areas/gautier-ms': typeof AreasGautierMsRoute
  '/areas/grand-bay-al': typeof AreasGrandBayAlRoute
  '/areas/moss-point-ms': typeof AreasMossPointMsRoute
  '/areas/ocean-springs-ms': typeof AreasOceanSpringsMsRoute
  '/areas/pascagoula-ms': typeof AreasPascagoulaMsRoute
  '/areas/theodore-al': typeof AreasTheodoreAlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bathroom-remodeling'
    | '/commercial-services'
    | '/contact'
    | '/drywall-services'
    | '/electrical-services'
    | '/estimate'
    | '/faq'
    | '/gallery'
    | '/general-contracting'
    | '/kitchen-remodeling'
    | '/painting-services'
    | '/plumbing-services'
    | '/renovation-services'
    | '/residential-services'
    | '/reviews'
    | '/service-areas'
    | '/areas/biloxi-ms'
    | '/areas/diberville-ms'
    | '/areas/gautier-ms'
    | '/areas/grand-bay-al'
    | '/areas/moss-point-ms'
    | '/areas/ocean-springs-ms'
    | '/areas/pascagoula-ms'
    | '/areas/theodore-al'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bathroom-remodeling'
    | '/commercial-services'
    | '/contact'
    | '/drywall-services'
    | '/electrical-services'
    | '/estimate'
    | '/faq'
    | '/gallery'
    | '/general-contracting'
    | '/kitchen-remodeling'
    | '/painting-services'
    | '/plumbing-services'
    | '/renovation-services'
    | '/residential-services'
    | '/reviews'
    | '/service-areas'
    | '/areas/biloxi-ms'
    | '/areas/diberville-ms'
    | '/areas/gautier-ms'
    | '/areas/grand-bay-al'
    | '/areas/moss-point-ms'
    | '/areas/ocean-springs-ms'
    | '/areas/pascagoula-ms'
    | '/areas/theodore-al'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bathroom-remodeling'
    | '/commercial-services'
    | '/contact'
    | '/drywall-services'
    | '/electrical-services'
    | '/estimate'
    | '/faq'
    | '/gallery'
    | '/general-contracting'
    | '/kitchen-remodeling'
    | '/painting-services'
    | '/plumbing-services'
    | '/renovation-services'
    | '/residential-services'
    | '/reviews'
    | '/service-areas'
    | '/areas/biloxi-ms'
    | '/areas/diberville-ms'
    | '/areas/gautier-ms'
    | '/areas/grand-bay-al'
    | '/areas/moss-point-ms'
    | '/areas/ocean-springs-ms'
    | '/areas/pascagoula-ms'
    | '/areas/theodore-al'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BathroomRemodelingRoute: typeof BathroomRemodelingRoute
  CommercialServicesRoute: typeof CommercialServicesRoute
  ContactRoute: typeof ContactRoute
  DrywallServicesRoute: typeof DrywallServicesRoute
  ElectricalServicesRoute: typeof ElectricalServicesRoute
  EstimateRoute: typeof EstimateRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  GeneralContractingRoute: typeof GeneralContractingRoute
  KitchenRemodelingRoute: typeof KitchenRemodelingRoute
  PaintingServicesRoute: typeof PaintingServicesRoute
  PlumbingServicesRoute: typeof PlumbingServicesRoute
  RenovationServicesRoute: typeof RenovationServicesRoute
  ResidentialServicesRoute: typeof ResidentialServicesRoute
  ReviewsRoute: typeof ReviewsRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  AreasBiloxiMsRoute: typeof AreasBiloxiMsRoute
  AreasDibervilleMsRoute: typeof AreasDibervilleMsRoute
  AreasGautierMsRoute: typeof AreasGautierMsRoute
  AreasGrandBayAlRoute: typeof AreasGrandBayAlRoute
  AreasMossPointMsRoute: typeof AreasMossPointMsRoute
  AreasOceanSpringsMsRoute: typeof AreasOceanSpringsMsRoute
  AreasPascagoulaMsRoute: typeof AreasPascagoulaMsRoute
  AreasTheodoreAlRoute: typeof AreasTheodoreAlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residential-services': {
      id: '/residential-services'
      path: '/residential-services'
      fullPath: '/residential-services'
      preLoaderRoute: typeof ResidentialServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovation-services': {
      id: '/renovation-services'
      path: '/renovation-services'
      fullPath: '/renovation-services'
      preLoaderRoute: typeof RenovationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plumbing-services': {
      id: '/plumbing-services'
      path: '/plumbing-services'
      fullPath: '/plumbing-services'
      preLoaderRoute: typeof PlumbingServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painting-services': {
      id: '/painting-services'
      path: '/painting-services'
      fullPath: '/painting-services'
      preLoaderRoute: typeof PaintingServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-remodeling': {
      id: '/kitchen-remodeling'
      path: '/kitchen-remodeling'
      fullPath: '/kitchen-remodeling'
      preLoaderRoute: typeof KitchenRemodelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general-contracting': {
      id: '/general-contracting'
      path: '/general-contracting'
      fullPath: '/general-contracting'
      preLoaderRoute: typeof GeneralContractingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrical-services': {
      id: '/electrical-services'
      path: '/electrical-services'
      fullPath: '/electrical-services'
      preLoaderRoute: typeof ElectricalServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drywall-services': {
      id: '/drywall-services'
      path: '/drywall-services'
      fullPath: '/drywall-services'
      preLoaderRoute: typeof DrywallServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-services': {
      id: '/commercial-services'
      path: '/commercial-services'
      fullPath: '/commercial-services'
      preLoaderRoute: typeof CommercialServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bathroom-remodeling': {
      id: '/bathroom-remodeling'
      path: '/bathroom-remodeling'
      fullPath: '/bathroom-remodeling'
      preLoaderRoute: typeof BathroomRemodelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/theodore-al': {
      id: '/areas/theodore-al'
      path: '/areas/theodore-al'
      fullPath: '/areas/theodore-al'
      preLoaderRoute: typeof AreasTheodoreAlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/pascagoula-ms': {
      id: '/areas/pascagoula-ms'
      path: '/areas/pascagoula-ms'
      fullPath: '/areas/pascagoula-ms'
      preLoaderRoute: typeof AreasPascagoulaMsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/ocean-springs-ms': {
      id: '/areas/ocean-springs-ms'
      path: '/areas/ocean-springs-ms'
      fullPath: '/areas/ocean-springs-ms'
      preLoaderRoute: typeof AreasOceanSpringsMsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/moss-point-ms': {
      id: '/areas/moss-point-ms'
      path: '/areas/moss-point-ms'
      fullPath: '/areas/moss-point-ms'
      preLoaderRoute: typeof AreasMossPointMsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/grand-bay-al': {
      id: '/areas/grand-bay-al'
      path: '/areas/grand-bay-al'
      fullPath: '/areas/grand-bay-al'
      preLoaderRoute: typeof AreasGrandBayAlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/gautier-ms': {
      id: '/areas/gautier-ms'
      path: '/areas/gautier-ms'
      fullPath: '/areas/gautier-ms'
      preLoaderRoute: typeof AreasGautierMsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/diberville-ms': {
      id: '/areas/diberville-ms'
      path: '/areas/diberville-ms'
      fullPath: '/areas/diberville-ms'
      preLoaderRoute: typeof AreasDibervilleMsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/biloxi-ms': {
      id: '/areas/biloxi-ms'
      path: '/areas/biloxi-ms'
      fullPath: '/areas/biloxi-ms'
      preLoaderRoute: typeof AreasBiloxiMsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BathroomRemodelingRoute: BathroomRemodelingRoute,
  CommercialServicesRoute: CommercialServicesRoute,
  ContactRoute: ContactRoute,
  DrywallServicesRoute: DrywallServicesRoute,
  ElectricalServicesRoute: ElectricalServicesRoute,
  EstimateRoute: EstimateRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  GeneralContractingRoute: GeneralContractingRoute,
  KitchenRemodelingRoute: KitchenRemodelingRoute,
  PaintingServicesRoute: PaintingServicesRoute,
  PlumbingServicesRoute: PlumbingServicesRoute,
  RenovationServicesRoute: RenovationServicesRoute,
  ResidentialServicesRoute: ResidentialServicesRoute,
  ReviewsRoute: ReviewsRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  AreasBiloxiMsRoute: AreasBiloxiMsRoute,
  AreasDibervilleMsRoute: AreasDibervilleMsRoute,
  AreasGautierMsRoute: AreasGautierMsRoute,
  AreasGrandBayAlRoute: AreasGrandBayAlRoute,
  AreasMossPointMsRoute: AreasMossPointMsRoute,
  AreasOceanSpringsMsRoute: AreasOceanSpringsMsRoute,
  AreasPascagoulaMsRoute: AreasPascagoulaMsRoute,
  AreasTheodoreAlRoute: AreasTheodoreAlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
